### ISSUE TITLE
More of a question.  Didn't know where to post

### ISSUE THREAD

**Issue by AmigaZoid** [KHerron/SonyAPILib#16]
I have full control of the TV using Amazon echo.  Thanks to you for the method to authenticate my PC.  My only issue is that when I issue a volume change, it works perfectly except for when I have a Sony sound bar on.  The volume change affects the Home screen but this value is not passed to system volume or the sound bar.  Seems to be a HDMI/ARC or CEC issue.  Any way to pass this volume change?

**Comment by KHerron** [comment]
Very strange. Have not ran in to this issue, nor do I have a sound bar.
I use a home theater amp (Sony STD-DN840) that controls my volume.
How are your components connected to each other?
Does the volume change work using the SonySideView or other app?
Does the volume change work using the original Sony remote control?

Try running my DLNA Control Panel example,
Load your device file, or Build it from the device document,
Click on the Rendering Control tab at the bottom,
Click on the "Get Volume" Execute button.
Then use the "Set Volume" option at the bottom right to the tab. 
(Enter a level different that is is now, then click execute.)
See if it changes the sound bar here. This is a totally different connection.

**Comment by AmigaZoid** [comment]
I'll try the app but having some problems getting the control panel to work.  I've registered this pc with the tv yet the control panel says "false" for registered. Here is some info, maybe you can point me in the right direction.  I'll try the android app also.

http://192.168.1.254:1990/WFADevice.xml
http://192.168.1.254:1990/WFADevice.xml
http://192.168.1.254:1990/WFADevice.xml
http://192.168.1.254:1990/WFADevice.xml
http://192.168.1.232:49310/device.xml
http://192.168.1.234:49200/device.xml
http://192.168.1.219:49200/device.xml
http://192.168.1.208:49200/device.xml
http://192.168.1.182:8008/ssdp/device-desc.xml
http://192.168.1.208:49310/device.xml
http://192.168.1.219:49310/device.xml
http://192.168.1.232:49200/device.xml
http://192.168.1.198:52323/dmr.xml
http://192.168.1.198:8008/ssdp/device-desc.xml
http://192.168.1.220:49310/device.xml
http://192.168.1.220:49200/device.xml
http://192.168.1.182:60600/dd.xml
http://192.168.1.234:49310/device.xml
http://192.168.1.198:64321/bar-sl-ms.xml
http://192.168.1.182:1812/

6/6/2017 6:15:42 PM - Clearing Log file: c:\ProgramData\Sony\SonyAPILib_LOG.txt
6/6/2017 6:16:07 PM - UPnP is Discovering devices....
6/6/2017 6:16:32 PM - Devices Discovered: 4
6/6/2017 6:16:59 PM - UPnP is Discovering devices....
6/6/2017 6:17:24 PM - Devices Discovered: 20
6/6/2017 6:20:16 PM - Retrieving Device Description Document from URI:
6/6/2017 6:20:16 PM - http://192.168.1.182:60600/dd.xml
6/6/2017 6:20:16 PM - Building Device from Document: http://192.168.1.182:60600/dd.xml
6/6/2017 6:20:16 PM - Document Found
6/6/2017 6:20:16 PM - Retrieving Controlling devices Mac Address. (this computer)
6/6/2017 6:20:16 PM - Mac Address retrieved: 02004C4F4F50
6/6/2017 6:20:16 PM - Re-Parsing Mac Address. (Replace : with -)
6/6/2017 6:20:16 PM - Mac Address has been re-Parsed: 02-00-4C-4F-4F-50
6/6/2017 6:20:16 PM - Verifing Registration for: XBR-55X930D
6/6/2017 6:20:16 PM - Checking Status of Device XBR-55X930D
6/6/2017 6:20:16 PM - Checking Device Status for XBR-55X930D Failed!
6/6/2017 6:20:16 PM - System.ArgumentNullException: Value cannot be null.
Parameter name: uriString
   at System.Uri..ctor(String uriString)
   at SonyAPILib.APILibrary.SonyDevice.HttpGet(String Url) in F:\OSA Files\Sony API\SonyAPILib_5.3\SonyAPILib\SonyAPILib\sonyAPILib.cs:line 555
   at SonyAPILib.APILibrary.SonyDevice.CheckStatus() in F:\OSA Files\Sony API\SonyAPILib_5.3\SonyAPILib\SonyAPILib\sonyAPILib.cs:line 796
6/6/2017 6:20:16 PM - XBR-55X930D: Registration Check returned: False
6/6/2017 6:20:16 PM - Can Not Retrieve Command List, No Registration
6/6/2017 6:20:16 PM - XBR-55X930D was built successfully.

6/6/2017 6:28:00 PM - Clearing Log file: c:\ProgramData\Sony\SonyAPILib_LOG.txt
6/6/2017 6:28:06 PM - Retrieving Device Description Document from URI:
6/6/2017 6:28:06 PM - http://192.168.1.182:26250/sony/webapi/ssdp/dd.xml
6/6/2017 6:28:06 PM - Building Device from Document: http://192.168.1.182:26250/sony/webapi/ssdp/dd.xml
6/6/2017 6:28:06 PM - Document Found
6/6/2017 6:28:06 PM - Retrieving Controlling devices Mac Address. (this computer)
6/6/2017 6:28:06 PM - Mac Address retrieved: 02004C4F4F50
6/6/2017 6:28:06 PM - Re-Parsing Mac Address. (Replace : with -)
6/6/2017 6:28:06 PM - Mac Address has been re-Parsed: 02-00-4C-4F-4F-50
6/6/2017 6:28:06 PM - IRCC:1 Service discovered on this device
6/6/2017 6:28:06 PM - Device has a registration Mode of: 3
6/6/2017 6:28:06 PM - Retrieving the Mac Address from: XBR-55X930D at IP: 192.168.1.182
6/6/2017 6:28:07 PM - Devices Mac Address: 18:4F:32:D9:0F:A3
6/6/2017 6:28:07 PM - Verifing Registration for: XBR-55X930D
6/6/2017 6:28:07 PM - Checking for Generation 3 Cookie
6/6/2017 6:28:07 PM - XBR-55X930D: Cookie Loaded: B585507929BABE3F693752FCACFA392CCB15E637
6/6/2017 6:28:07 PM - XBR-55X930D: Getting Country Date/Time format
6/6/2017 6:28:07 PM - XBR-55X930D: System Culture Date/Time format is: M/d/yyyy
6/6/2017 6:28:07 PM - No Cookie was found
6/6/2017 6:28:07 PM - System.Globalization.CultureNotFoundException: Culture is not supported.
Parameter name: name
M/d/yyyy is an invalid culture identifier.
   at System.Globalization.CultureInfo..ctor(String name, Boolean useUserOverride)
   at SonyAPILib.APILibrary.SonyDevice.CheckReg() in F:\OSA Files\Sony API\SonyAPILib_5.3\SonyAPILib\SonyAPILib\sonyAPILib.cs:line 708
6/6/2017 6:28:07 PM - XBR-55X930D: Registration Check returned: False
6/6/2017 6:28:07 PM - Can Not Retrieve Command List, No Registration
6/6/2017 6:28:07 PM - XBR-55X930D was built successfully.

My setup is the TV connected by wifi and the sony soundbar (192.168.1.198 from above list) through HDMI4/ARC which is the HDMI-CEC.
After doing some digging, I found that this is not "speaker" output but systemaudio or something like that.  Thanks for any help you can offer.

--------------------------------------------
On Tue, 6/6/17, Kirk <notifications@github.com> wrote:

 Subject: Re: [KHerron/SonyAPILib] More of a question. Didn't know where to post (#16)
 To: "KHerron/SonyAPILib" <SonyAPILib@noreply.github.com>
 Cc: "AmigaZoid" <dtorres1966@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Tuesday, June 6, 2017, 5:09 PM
 
 Very strange. Have not ran in to
 this issue, nor do I have a sound bar.
 
 I use a home theater amp (Sony STD-DN840) that controls my
 volume.
 
 How are your components connected to each other?
 
 Does the volume change work using the SonySideView or other
 app?
 
 Does the volume change work using the original Sony remote
 control?
 Try running my DLNA Control Panel example,
 
 Load your device file, or Build it from the device
 document,
 
 Click on the Rendering Control tab at the bottom,
 
 Click on the "Get Volume" Execute button.
 
 Then use the "Set Volume" option at the bottom
 right to the tab.
 
 (Enter a level different that is is now, then click
 execute.)
 
 See if it changes the sound bar here. This is a totally
 different connection.
 
 —
 You are
 receiving this because you authored the thread.
 Reply
 to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by AmigaZoid** [comment]
Found an app that the volume control affects the correct tv volume and the soundbar just like the original sony remote.  I'll do some sniffing.

**Comment by KHerron** [comment]
The correct URL above to Build from Document would be:
http://192.168.1.198:52323/dmr.xml

**Comment by KHerron** [comment]
@AmigaZoid,

Going back through these issues to clear them out, as was wondering if you solved your issue, and was there some information I could use to correct it in my API?

Thanks..
Kirk
