### ISSUE TITLE
2011 AV Amp STR-DN1030

### ISSUE THREAD

**Issue by PaulWebster** [KHerron/SonyAPILib#25]
I am experimenting with my Sony TV and Amp - both from around 2011.
I have the TV working - using the ConsoleExample.exe to check things out.
However, the Amp is not getting through the registration phase with ConsoleExample.exe

I don't have the tools to build from source - but my intention, once I get things working, is to merge some equivalent functions back into some Python code that, today, only handles newer generation devices.

The Amp is on the list as supported - STR-DN1030 is a "mode 1" device for registration.
...:50001/cers/ActionList.xml
contains
```
<actionList>
<action name="register" mode="1" url="http://192.168.2.140:50001/cers/register"/>
<action name="getSystemInformation" url="http://192.168.2.140:50001/cers/getSystemInformation"/>
<action name="getRemoteCommandList" url="http://192.168.2.140:50001/cers/getRemoteCommandList"/>
<action name="getStatus" url="http://192.168.2.140:50001/cers/getStatus"/>
<action name="getText" url="http://192.168.2.140:50001/cers/getText"/>
<action name="sendText" url="http://192.168.2.140:50001/cers/sendText"/>
</actionList>

```

To try to understand what needs to be sent and checked for, I was looking in sonyAPILib.cs and saw this
```

                if (this.Actionlist.RegisterMode == 1)
                {
                    reg = HttpGet(this.Actionlist.RegisterUrl + "?" + args1);
                    _Log.AddMessage("Register Mode: 2 Sony Device", false);
                }
                else if (this.Actionlist.RegisterMode == 2)
                {
                    reg = HttpGet(this.Actionlist.RegisterUrl + "?" + args2);
                    _Log.AddMessage("Register Mode: 1 Sony Device", false);
                }
```
I am sure it is correct as you have said that you have an old Amp as well - but the log entries appear to be the wrong way around (if mode==1 then log as "2" )

In the Amp I have a menu item for access control - including the ability to have "auto" enabled or not - I have tried both ways.
I have had a new id appear under the list of devices with access - although the id is not very meaningful (I cannot use it to determine what the other 3 control devices are).

Is there an API call to access the list of accepted control devices and perhaps get more details about them?

The Amp info is at ...:8080/description.xml
and contains - among other stuff...
```
<device>
<av:X_UNR_DeviceInfo xmlns:av="urn:schemas-sony-com:av">
<av:X_UNR_Version>1.2</av:X_UNR_Version>
<av:X_CERS_ActionList_URL>http://192.168.2.140:50001/cers/ActionList.xml</av:X_CERS_ActionList_URL>
<av:X_Remote_Type>RM-AAP078</av:X_Remote_Type>
<av:X_Remote_Type>RM-AAP079</av:X_Remote_Type>
</av:X_UNR_DeviceInfo>
</device>
```

and ...:50001/cers/ActionList.xml contains
```
<actionList>
<action name="register" mode="1" url="http://192.168.2.140:50001/cers/register"/>
<action name="getSystemInformation" url="http://192.168.2.140:50001/cers/getSystemInformation"/>
<action name="getRemoteCommandList" url="http://192.168.2.140:50001/cers/getRemoteCommandList"/>
<action name="getStatus" url="http://192.168.2.140:50001/cers/getStatus"/>
<action name="getText" url="http://192.168.2.140:50001/cers/getText"/>
<action name="sendText" url="http://192.168.2.140:50001/cers/sendText"/>
</actionList>
```
and
and
```
<device>
<servicelist>
<service>
<serviceType>urn:schemas-sony-com:service:IRCC:1</serviceType>
<serviceId>urn:schemas-sony-com:serviceId:IRCC</serviceId>
<SCPDURL>/IRCCSCPD.xml</SCPDURL>
<controlURL>/upnp/control/IRCC</controlURL>
<eventSubURL>/</eventSubURL>
</service>
</serviceList>
</device>
```

**Comment by KHerron** [comment]
>                 if (this.Actionlist.RegisterMode == 1)
>                 {
>                     reg = HttpGet(this.Actionlist.RegisterUrl + "?" + args1);
>                     _Log.AddMessage("Register Mode: 2 Sony Device", false);
>                 }
>                 else if (this.Actionlist.RegisterMode == 2)
>                 {
>                     reg = HttpGet(this.Actionlist.RegisterUrl + "?" + args2);
>                     _Log.AddMessage("Register Mode: 1 Sony Device", false);
>                 }
> 
> I am sure it is correct as you have said that you have an old Amp as well - but the log entries appear to be the wrong way around (if mode==1 then log as "2" )

Disregard this, as it was not corrected in the text. It is suppose to be "Generation" not Mode. But it IS CORRECT, so DO NOT CHANGE it. 

AS far as your amp goes, you will need to have it connected to your TV with HDMI, and you will need to go into the network settings and find where you put the AMP in "Registration Mode". You will only have about 30 - 45 seconds to run the registration code while the AMP is in registration mode. If successfu7l, you should be able to see it on the TV. You may need to refer to your manual for the exact instructions.

Let me know if you have any other issues.

**Comment by PaulWebster** [comment]
I have the Amp working with Sony TV Sideview and have been to the same registration enablement page in the Amp (different menu structure to the TV so I know it is from the Amp) - long long ago.
I'll run ConsoleExample and Sideview through a proxy to see if I can spot differences - and can also delete the Sideview registration from the Amp to force it through the process again.

Have also downloaded free version of Visual Studio 2017 to see if I can build my own copy and run it with a debugger to see what it really sees.

**Comment by PaulWebster** [comment]
FYI - and this could easily be down to inexperience and misconfiguration ...
I installed VS 2017 and tried to build ConsoleExample - but it failed because it did not like
TextWriter writer = new StreamWriter(mySonyDevice.Name + ".xml");
(around line 392)
I resolved it by adding
using System.IO;
after line 5

**Comment by PaulWebster** [comment]
Found a solution
The Amp insists on "MediaRemote" being used in the deviceId
Log of failure - from yesterday (lightly edited to replace MAC info not that it is much use to anyone else)
```
13/12/2018 14:21:06 - STR-DN1030: Registration Check returned: False
13/12/2018 14:21:10 - Controlling Mac address: 11-22-33-44-55-66
13/12/2018 14:21:10 - Creating HttpWebRequest to URL: http://192.168.2.140:50001/cers/register?name=PAUL1(SonyAPILib)&registrationType=initial&deviceId=TVSideView%3A11-22-33-44-55-66 
13/12/2018 14:21:10 - Setting Header Information: 192.168.2.140:50001
13/12/2018 14:21:10 - Creating Web Request Response
13/12/2018 14:22:00 - There was an error during the Web Request or Response! System.Net.WebException: The underlying connection was closed: The connection was closed unexpectedly.
   at System.Net.HttpWebRequest.GetResponse()
   at SonyAPILib.APILibrary.SonyDevice.HttpGet(String Url) in \\Ccsg\f\OSA Files\Sony API\SonyAPILib_5.4\SonyAPILib\SonyAPILib\sonyAPILib.cs:line 624
13/12/2018 14:22:00 - Register Mode: 2 Sony Device
13/12/2018 14:22:00 - Registration was NOT successful for device at: 192.168.2.140
13/12/2018 14:22:00 - Saving API Device file for: STR-DN1030 F738DC
13/12/2018 14:22:00 - Success: Saved API Device file: STR-DN1030 F738DC
```
I changed the code to replace "TVSideView" with "MediaRemote" in the URL and in the header ... and then success ...

```
14/12/2018 15:06:56 - STR-DN1030: Registration Check returned: False
14/12/2018 15:07:02 - Controlling Mac address: 11-22-33-44-55-66
14/12/2018 15:07:02 - Creating HttpWebRequest to URL: http://192.168.2.140:50001/cers/register?name=PAUL1(SonyAPILib)&registrationType=initial&deviceId=MediaRemote%3A11-22-33-44-55-66 
14/12/2018 15:07:02 - Setting Header Information: 192.168.2.140:50001
14/12/2018 15:07:02 - Creating Web Request Response
14/12/2018 15:07:02 - Executing StreamReader
14/12/2018 15:07:02 - Response returned: 
14/12/2018 15:07:02 - Register Mode: 2 Sony Device
14/12/2018 15:07:02 - Registration was Successful for device at: 192.168.2.140
14/12/2018 15:07:02 - Saving API Device file for: STR-DN1030 F738DC
14/12/2018 15:07:02 - Success: Saved API Device file: STR-DN1030 F738DC

```
This solution has been found before
https://community.openhab.org/t/sony-devices-binding/14052/182
If other Sony Bravia kit does not check it (which is the implication from the OpenHAB discussions) then I suspect it is safe to include this as the default.
