### ISSUE TITLE
Registration failed (KDL-52W5500)

### ISSUE THREAD

**Issue by SimFre** [KHerron/SonyAPILib#26]
I've just found this library, and am hoping that it would work on KDL-52W5500. However, it seems not based on the compatibility list and this message I'm getting. To start with, perhaps I've got the registration wrong. I can cast media from the laptop to the TV via DLNA. When I look into Settings / Network / Renderer Access Control, where I can see the MAC-address of the laptop listed as Permission=On. Is this the only registration, or is there any other?

`SonyAPILib v5.3 by: Kirk Herron
Starting Console Example Program
================================
Searching for Devices...
Device Count: 1
---------------------------------
0 - http://192.168.5.116:52323/dmr.xml
---------------------------------
Enter the Device # to Test
0

http://192.168.5.116:52323/dmr.xml: Building Device....
BRAVIA KDL-52W5500: Checking Device Status....

Get Status returned: Error
---------------------------------

BRAVIA KDL-52W5500: Performing Registration....
Before continuing, you may need to set the device to Registration Mode,
Confirm Registration or enter the Registration PIN code.
Go to the device and perfrom any step, and be ready before hitting enter below!
=====================================
Hit any key to continue
Registration returned: False
---------------------------------

There was an error
---------------------------------

BRAVIA KDL-52W5500: Retrieving Remote Command List
ERROR Retrieving Command List
---------------------------------

BRAVIA KDL-52W5500: Retrieving Command Value for: VolumeUp

Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at SonyAPILib.APILibrary.SonyDevice.GetCommandString(String CmdName) in \\Ccsg\f\OSA Files\Sony API\SonyAPILib_5.4\SonyAPILib\SonyAPILib\sonyAPILib.cs:line 947
   at ConsoleExample.Program.Main(String[] args) in \\Ccsg\f\OSA Files\Sony API\SonyAPILib_5.4\ConsoleExample\Program.cs:line 286`

**Comment by KHerron** [comment]
We have had this issue before, and if it's not on the compatibility list, then It is most likely not going work. How old is this TV? Have you tried to download and use the "Sony Virtual Remote" app? I believe it is available for IOS, Android and PC. It is based on the same technology as my API.
